apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: graf
    app.kubernetes.io/managed-by: Helm
  name: graf
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: graf
  type: NodePort
status:
  loadBalancer: {}